server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: "${DATABASE_URL}" # 90 days
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
    driverClassName: org.postgresql.Driver

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY} #Random
      expiration: 86400000 # One day
      refresh-token:
        expiration: 604800000 # 7 days