server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
#      ddl-auto: update
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: "jdbc:postgresql://dpg-clajgrunt67s738ngk30-a.oregon-postgres.render.com:5432/guitar_shop_db"
    username: ticket_app_f5o4_user
    password: 7sSwpZA9J3Ws95MFddHuFNIbDutVWjtl
    driverClassName: org.postgresql.Driver